### ISSUE TITLE
rawContent

### ISSUE THREAD

**Issue by majad-in** [josephj/react-icalendar-link#15]
Warning: React does not recognize the `rawContent` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `rawcontent` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

**Comment by thomas-kahn** [comment]
I'm experiencing this as well.

**Comment by josephj** [comment]
Fixed

**Comment by majad-in** [comment]
> Fixed https://www.npmjs.com/package/react-icalendar-link/v/3.0.2

I have tested, though not working on iOS/chrome

**Comment by josephj** [comment]
Hey @majad-in, This one is just for fixing the `rawContent` prop warning issue. For supporting the iOS Chrome or other browsers to work, please refer to the following one. https://github.com/josephj/react-icalendar-link/issues/3#issuecomment-770320533 😢
