### ISSUE TITLE
JSX element class does not support attributes because it does not have a 'props' property.

### ISSUE THREAD

**Issue by clayosborn** [josephj/react-icalendar-link#25]
Get the error "JSX element class does not support attributes because it does not have a 'props' property." when implementing the very example provided on the usage page.

**Comment by josephj** [comment]
@clayosborn I don't see any JSX warning from my example. And can't see anything from the code-level too. Do you mind giving me an example?

<img width="1607" alt="CleanShot 2022-02-19 at 05 33 26@2x" src="https://user-images.githubusercontent.com/136648/154742290-bcc01005-98ca-4b38-be7c-8cc8005ee8c0.png">
