### ISSUE TITLE
Any way to change the file name?

### ISSUE THREAD

**Issue by chocobuckle** [josephj/react-icalendar-link#26]
At the moment it just downoads as 'download.ics'.

**Comment by josephj** [comment]
@chocobuckle Yes, you can use `filename` which was an undocumented prop. I have updated the `README.md` file as well. 

https://github.com/josephj/react-icalendar-link#using-a-different-file-name

```jsx
        <ICalLink event={event} filename="have-a-nice-day.ics" style={style} rawContent={rawContent}>
          Today is a huge day!
        </ICalLink>
```
