### ISSUE TITLE
When generating link in chrome mobile opens a blank window with blob text file

### ISSUE THREAD

**Issue by ratnev** [josephj/react-icalendar-link#3]
Is there is a way to add support for chrome mobile?

**Comment by josephj** [comment]
@ratnev 

There is a known chromium bug while I wrote this. iOS Chrome doesn't support adding to iCal at the moment. 
https://bugs.chromium.org/p/chromium/issues/detail?id=666211

Currently I can't find this bug anymore. 

You can use `ICalLink.isSupported()` to exclude the Chrome mobile browser.

**Comment by xrzhuang** [comment]
is this why when i try to click on this from chrome responsive view during local development, nothing happens?

**Comment by josephj** [comment]
@xrzhuang not sure, I can still download the ics when it's chrome responsive mode.

![image](https://user-images.githubusercontent.com/136648/119071965-0cbe6b80-ba2e-11eb-9edc-68d944a5c2ce.png)

**Comment by xrzhuang** [comment]
actually using your link, I am observing the same behavior, try changing the responsive view to `iphone x` or something

**Comment by josephj** [comment]
@xrzhuang  it still works for me. 

![image](https://user-images.githubusercontent.com/136648/119903826-a2a54980-bf8c-11eb-9acd-f1ac66a5f201.png)

![image](https://user-images.githubusercontent.com/136648/119903845-ac2eb180-bf8c-11eb-8439-5d114bfc23f4.png)

Even it's not working for you, just feel curious with the reason you want to make it work in the devtool responsive view. Automated E2E or manual testing should be working fine.

**Comment by josephj** [comment]
Closing since it doesn't have more responses
