### ISSUE TITLE
Support for React 17?

### ISSUE THREAD

**Issue by geekus** [josephj/react-icalendar-link#5]
We use React 17 in our project and get dependency conflicts trying to install this package. Would supporting React 17 require any changes to the package?

**Comment by josephj** [comment]
Will do

**Comment by geekus** [comment]
Thanks a bunch! 🤩

**Comment by josephj** [comment]
@geekus You can try version `2.0.2`. I actually just update the `peerDepencies` version to `>= 15.0.0`. Hopefully it works.

**Comment by geekus** [comment]
Yes, now it worked. Thanks again. ☺️
